version: '3.8'

services:
  startgeek:
    image: node:18-alpine
    container_name: StartGeek
    restart: unless-stopped
    ports:
      - "3000:3000"
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm install && npm run build && npm run serve"
    environment:
      - NODE_ENV=production